logging:
  level:
    com.example.apigateway: debug

spring:
  cloud:
    gateway:
      default-filters:
        - name: CustomGlobalGatewayFilter # Global filter class파일 명
          args: # static Config class에 전달할 값 정의
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
#            - QueryParam=id
#            - name: QueryParam
#              args:
#                param: id
          filters:
            - AddRequestHeader=user-request, user-request-header
            - AddResponseHeader=user-response, user-response-header
            - CustomUserFilter
            - JwtAuthorization=ROLE_ADMIN
#            - SetPath=/user/{id}
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
          filters:
            - AddRequestHeader=product-request, product-request-header
            - AddResponseHeader=product-response, product-response-header


jwt:
  secret: secret
  expiration-second: 28800