spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - AddRequestParameter=name, kim

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
